# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-19 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_eag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='eag',
            new_name='age',
        ),
    ]
